// GENERATED by scripts/qa_frontend_palette.py --emit-ts — do not edit.
//
// Hex rather than OKLCH on purpose: MapLibre's colour parser handles only
// named / hex / rgb() / hsl(). An oklch() value fails style validation and
// the layer silently falls back to the property default.
//
// Regenerate:  python3 scripts/qa_frontend_palette.py --emit-ts \
//                > frontend/src/design/palette.generated.ts

export const palette = {
  light: {
    canvas: '#f6fbfc',
    surface: '#ffffff',
    surface_2: '#ebf4f4',
    hairline: '#d4e1e2',
    hairline_2: '#bccfd0',
    ink_3: '#627476',
    ink_2: '#3b5254',
    ink: '#0c2327',
    accent: '#117780',
    ink_inverse: '#e2eeee',
    risk: {
      minimal: '#e2ded0',
      low: '#e4c898',
      moderate: '#e2a055',
      high: '#d67229',
      critical: '#b93c27',
    },
    riskStroke: {
      minimal: '#e4c898',
      low: '#e2a055',
      moderate: '#d67229',
      high: '#b93c27',
      critical: '#0c2327',
    },
    data_measured: '#3b5254',
    data_modelled: '#627476',
  },
  dark: {
    canvas: '#041418',
    surface: '#0c1f23',
    surface_2: '#152a2f',
    hairline: '#26393d',
    hairline_2: '#364c51',
    ink_3: '#778a8d',
    ink_2: '#a9bbbd',
    ink: '#e2eeee',
    accent: '#56ccd2',
    ink_inverse: '#0c2327',
    risk: {
      minimal: '#554d30',
      low: '#7e612c',
      moderate: '#ae7129',
      high: '#e17a39',
      critical: '#f98368',
    },
    riskStroke: {
      minimal: '#7e612c',
      low: '#ae7129',
      moderate: '#e17a39',
      high: '#f98368',
      critical: '#e2eeee',
    },
    data_measured: '#a9bbbd',
    data_modelled: '#778a8d',
  },
} as const;

export type ThemeName = keyof typeof palette;
