// GENERATED by scripts/qa_frontend_palette.py --emit-ts — do not edit.
//
// Hex rather than OKLCH on purpose: MapLibre's colour parser handles only
// named / hex / rgb() / hsl(). An oklch() value fails style validation and
// the layer silently falls back to the property default.
//
// Regenerate:  python3 scripts/qa_frontend_palette.py --emit-ts \
//                > frontend/src/design/palette.generated.ts

export const palette = {
  light: {
    canvas: '#f4f7fa',
    surface: '#ffffff',
    surface_2: '#e6f7fa',
    hairline: '#dce5ec',
    hairline_2: '#c3d0da',
    ink_3: '#607086',
    ink_2: '#46566d',
    ink: '#0a1f4d',
    accent: '#027998',
    ink_inverse: '#e4f1f3',
    risk: {
      minimal: '#e2ded0',
      low: '#e4c898',
      moderate: '#e2a055',
      high: '#d67229',
      critical: '#b93c27',
    },
    riskStroke: {
      minimal: '#e4c898',
      low: '#e2a055',
      moderate: '#d67229',
      high: '#b93c27',
      critical: '#0a1f4d',
    },
    data_measured: '#46566d',
    data_modelled: '#607086',
  },
  dark: {
    canvas: '#09111f',
    surface: '#121c2d',
    surface_2: '#1b263a',
    hairline: '#2b3647',
    hairline_2: '#3c485b',
    ink_3: '#798898',
    ink_2: '#aec2c8',
    ink: '#e4f1f3',
    accent: '#08b7c3',
    ink_inverse: '#0a1f4d',
    risk: {
      minimal: '#554d30',
      low: '#7e612c',
      moderate: '#ae7129',
      high: '#e17a39',
      critical: '#f98368',
    },
    riskStroke: {
      minimal: '#7e612c',
      low: '#ae7129',
      moderate: '#e17a39',
      high: '#f98368',
      critical: '#e4f1f3',
    },
    data_measured: '#aec2c8',
    data_modelled: '#798898',
  },
} as const;

export type ThemeName = keyof typeof palette;
