/** Stylelint is one of three layers enforcing 06-bilingual-rtl.md §2.
 *
 *  It covers hand-written CSS. oxlint covers correctness in TS/TSX but has no
 *  `no-restricted-syntax`, so it cannot catch physical Tailwind classes — that
 *  falls to scripts/qa_frontend_rtl.py, which also sees template literals, JSX
 *  class strings and the `rtl-ok:` exception mechanism.
 *
 *  A JS config rather than JSON so each decision can carry its reason.
 */
export default {
  extends: ['stylelint-config-standard'],
  plugins: ['stylelint-use-logical'],

  ignoreFiles: [
    '**/node_modules/**',
    // generated by scripts/qa_frontend_palette.py --emit-css; checked instead by
    // scripts/qa_frontend_tokens.py, which compares it byte-for-byte
    'src/styles/tokens.generated.css',
    'public/**',
    'dist/**',
  ],

  rules: {
    // The rule that prevents the rewrite. 06 §2: never write a physical
    // direction — not in a component, not in a one-off fix, not "just this once".
    'csstools/use-logical': 'always',

    // Belt to use-logical's braces: it also catches the shorthand and radius
    // corners, which are easy to reach for without thinking about direction.
    'property-disallowed-list': [
      [
        'margin-left',
        'margin-right',
        'padding-left',
        'padding-right',
        'left',
        'right',
        'border-left',
        'border-right',
        'border-left-width',
        'border-right-width',
        'border-left-color',
        'border-right-color',
        'border-left-style',
        'border-right-style',
        'border-top-left-radius',
        'border-top-right-radius',
        'border-bottom-left-radius',
        'border-bottom-right-radius',
        'float',
        'clear',
      ],
      {
        severity: 'error',
        message:
          'Physical direction. Use the logical property (margin-inline-start, inset-inline-end, border-inline-start, border-start-start-radius). 06-bilingual-rtl.md §2.',
      },
    ],

    'declaration-property-value-disallowed-list': {
      'text-align': ['/^(left|right)$/'],
      'transform-origin': ['/\\b(left|right)\\b/'],
    },

    // Tailwind v4 at-rules. Without this every one of them reads as a typo.
    'at-rule-no-unknown': [
      true,
      {
        ignoreAtRules: [
          'theme',
          'source',
          'utility',
          'variant',
          'custom-variant',
          'apply',
          'reference',
          'config',
          'plugin',
          'layer',
        ],
      },
    ],

    // Off because Tailwind v4's own syntax is not kebab-case: `--color-*: initial`
    // clears a namespace, and `--text-xs--line-height` /
    // `--font-mono--font-feature-settings` are its modifier form. Both are valid,
    // and both are required by theme.css.
    'custom-property-pattern': null,

    // Off so hand-written oklch() matches the format the generator emits.
    // Stylelint prefers `oklch(18% 0.024 215deg / 16%)`; qa_frontend_palette.py
    // writes `oklch(0.180 0.024 215)`. One notation across generated and
    // hand-written CSS is worth more than stylelint's preference here.
    'lightness-notation': null,
    'hue-degree-notation': null,
    'alpha-value-notation': null,

    'import-notation': 'string',
    'custom-property-empty-line-before': null,
    'declaration-empty-line-before': null,
    'comment-empty-line-before': null,
    'no-descending-specificity': null,
  },
};
