#!/usr/bin/env python3
"""Re-examine the Oct 2016 ordering anomaly over the corrected extent.

The anomaly, as recorded in docs/event_dates.md
-----------------------------------------------
The derived rainfall peak falls AFTER the documented flood arrival:

    peak 3 h window   2016-10-28T02:30Z .. 05:30Z   (derived from IMERG)
    flood arrival     2016-10-28T00:00Z             (reported, Kalman 2025)

which is the opposite of the paper's own sequence — it states the flood
reached the sea about 3 hours after most rainfall had ended. That file names
the suspected cause:

    "The likely explanation is spatial: the ~11 km IMERG cell and this small
    padded box sample coastal rainfall, while the flood was generated by
    rainfall over upstream catchments that may lie largely OUTSIDE
    DOWNLOAD_BBOX. Resolve this once real catchment polygons exist —
    recompute over the catchments, not the box."

Both preconditions now hold: the catchments exist, and the event has been
re-fetched over the terrain AOI. This script does the recomputation.

It does not assume the anomaly resolves. It reports what the data says.
"""

from __future__ import annotations

import json
import logging
import sys
from datetime import datetime, timezone
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "backend" / "src"))

import pandas as pd  # noqa: E402

from config.spatial import TERRAIN_AOI  # noqa: E402
from ingestion.imerg import process_imerg_window  # noqa: E402
from processing.catchment_rainfall import (  # noqa: E402
    aggregate_catchment_rainfall,
    build_grid_cells,
    compute_overlaps,
    load_catchments,
    wettest_windows_per_catchment,
)

EVENT_ID = "AQ-2016-10-28"
GRANULES = PROJECT_ROOT / "data" / "raw" / "imerg" / "events" / EVENT_ID
RETIRED = PROJECT_ROOT / "data" / "raw" / "imerg" / "events" / f"{EVENT_ID}_RETIRED_BOX"
CATCHMENTS = PROJECT_ROOT / "data" / "processed" / "vectors" / "catchments.gpkg"
OUT = PROJECT_ROOT / "data" / "processed" / "events" / "ordering_anomaly_analysis.json"

#: Reported by Kalman et al. (2025), timezone-converted in docs/event_dates.md.
FLOOD_ARRIVAL_UTC = pd.Timestamp("2016-10-28T00:00:00Z")
OFFSHORE_RESPONSE_UTC = pd.Timestamp("2016-10-28T06:50:00Z")

#: The old result, over the retired box, for side-by-side comparison.
OLD_PEAK_3H_START = "2016-10-28T02:30:00Z"
OLD_PEAK_3H_MM = 11.715

logging.basicConfig(level=logging.INFO, format="%(message)s")
logger = logging.getLogger("anomaly")


def main() -> int:
    paths = sorted(GRANULES.glob("*.nc*"))
    if not paths:
        logger.error("no granules in %s — run scripts/sweep_imerg_halfhourly.py "
                     "--literature", GRANULES)
        return 1

    catchments = load_catchments(CATCHMENTS)
    logger.info("Ordering anomaly — recomputed over real catchments")
    logger.info("  granules    %d", len(paths))
    logger.info("  extent      %s (terrain AOI)", TERRAIN_AOI)
    logger.info("  catchments  %d\n", len(catchments))

    combined = process_imerg_window(
        paths, rolling_windows_hours=(1, 3, 6, 24), run_type="final",
        bbox=TERRAIN_AOI.wsen,
    )
    overlaps = compute_overlaps(build_grid_cells(combined), catchments)
    frame = aggregate_catchment_rainfall(
        combined, overlaps, event_id=EVENT_ID, geometry_status="REAL",
    )

    peaks = wettest_windows_per_catchment(frame, interval_hours=0.5)

    logger.info("Wettest 3 h window per catchment, over the catchment itself:")
    logger.info(f"  {'catchment':10} {'start (UTC)':22} {'mm':>7}  vs flood arrival")
    rows = []
    for catchment_id in sorted(peaks):
        window = peaks[catchment_id].get("rain_3h_mm")
        if not window:
            continue
        start = pd.Timestamp(window["start_utc"])
        lead_hours = (FLOOD_ARRIVAL_UTC - start).total_seconds() / 3600.0
        verdict = "BEFORE" if lead_hours > 0 else "after"
        logger.info("  %-10s %-22s %7.3f  %+6.1f h %s",
                    catchment_id, window["start_utc"], window["max_mm"],
                    lead_hours, verdict)
        rows.append({
            "catchment_id": catchment_id,
            "peak_3h_start_utc": window["start_utc"],
            "peak_3h_end_utc": window["end_utc"],
            "peak_3h_mm": round(float(window["max_mm"]), 4),
            "hours_before_flood_arrival": round(lead_hours, 2),
            "precedes_flood_arrival": bool(lead_hours > 0),
        })

    # AQ-C01 is the one that matters: Wadi Yutum carries 96 % of the discharge
    # and Kalman et al. name it explicitly as a generating catchment.
    primary = next((r for r in rows if r["catchment_id"] == "AQ-C01"), None)
    resolved = bool(primary and primary["precedes_flood_arrival"])

    logger.info("")
    logger.info("Old result, over the retired box:")
    logger.info("  peak 3 h at %s, %.3f mm  (%.1f h AFTER arrival)",
                OLD_PEAK_3H_START, OLD_PEAK_3H_MM,
                (pd.Timestamp(OLD_PEAK_3H_START) - FLOOD_ARRIVAL_UTC).total_seconds() / 3600)
    if primary:
        logger.info("New result, over Wadi Yutum (AQ-C01):")
        logger.info("  peak 3 h at %s, %.3f mm  (%+.1f h)",
                    primary["peak_3h_start_utc"], primary["peak_3h_mm"],
                    primary["hours_before_flood_arrival"])

    logger.info("")
    logger.info("VERDICT: %s", "RESOLVED — rainfall now precedes the flood"
                if resolved else
                "NOT RESOLVED — the peak still follows the reported arrival")

    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(json.dumps({
        "generated_utc": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "event_id": EVENT_ID,
        "question": (
            "Does the derived rainfall peak precede the documented flood "
            "arrival once computed over the real catchments rather than the "
            "retired coastal box?"
        ),
        "reported_flood_arrival_utc": str(FLOOD_ARRIVAL_UTC),
        "reported_offshore_response_utc": str(OFFSHORE_RESPONSE_UTC),
        "extent": {"terrain_aoi_wsen": list(TERRAIN_AOI.wsen)},
        "granules_used": len(paths),
        "old_result_over_retired_box": {
            "peak_3h_start_utc": OLD_PEAK_3H_START,
            "peak_3h_mm": OLD_PEAK_3H_MM,
            "precedes_flood_arrival": False,
        },
        "per_catchment": rows,
        "resolved": resolved,
        "note": (
            "Computed over catchment polygons, not a bounding box. AQ-C01 is "
            "decisive: it carries 96 % of the discharge and Kalman et al. "
            "(2025) name Wadi Yutum explicitly as a generating catchment."
        ),
    }, indent=2) + "\n")
    logger.info("wrote %s", OUT.relative_to(PROJECT_ROOT))
    return 0


if __name__ == "__main__":
    sys.exit(main())
