"""Shared plumbing for QA figures: captioning, timestamping, manifest, basemaps.

Standing rule for this phase: if it isn't visible it isn't verified; if it's
verified it's screenshotted; if it's screenshotted it's named, captioned and
linked. `save_fig` enforces the last three mechanically so a figure cannot be
produced without a caption, and the manifest cannot drift from what is on disk.

Naming convention: <source>_<NN>_<description>.png
"""

import datetime as _dt
import json
import warnings

import contextily as cx
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from config import QA

warnings.filterwarnings("ignore", category=UserWarning)

MANIFEST_JSON = QA / "manifest.json"
MANIFEST_MD = QA / "MANIFEST.md"

# Web Mercator: the native CRS of the tile providers. Basemap figures are drawn
# in 3857 rather than 4326 so tiles are used unwarped and at full sharpness, and
# so no aspect correction is needed (Mercator is conformal — shapes are locally
# true, which is the property a visual check depends on).
CRS_BASEMAP = "EPSG:3857"

SATELLITE = cx.providers.Esri.WorldImagery


def add_satellite(ax, zoom=13, attribution_size=5):
    """Esri WorldImagery under the current axes. Axes must already be in 3857."""
    try:
        cx.add_basemap(ax, source=SATELLITE, zoom=zoom, crs=CRS_BASEMAP,
                       attribution_size=attribution_size)
        return True
    except Exception as e:  # offline / tile server hiccup must not kill the run
        print(f"    ! basemap unavailable ({type(e).__name__}) — plotting without it")
        return False


def save_fig(fig, name, caption, source, dpi=150):
    """Save under QA/, stamp caption + UTC timestamp on the image, record it.

    `caption` is mandatory and is burned into the figure itself, so an image that
    gets copied into a slide deck still carries its own explanation.
    """
    if not name.endswith(".png"):
        name += ".png"
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    fig.text(0.005, 0.004, caption, ha="left", va="bottom", fontsize=7.5,
             color="#222222", wrap=True)
    fig.text(0.995, 0.004, f"ReefShield Aqaba · Pulga · {stamp}", ha="right",
             va="bottom", fontsize=6.5, color="#777777")

    QA.mkdir(parents=True, exist_ok=True)
    path = QA / name
    fig.savefig(path, dpi=dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    _record(name, caption, source, stamp)
    print(f"    {name}")
    return path


def _record(name, caption, source, stamp):
    data = {}
    if MANIFEST_JSON.exists():
        try:
            data = json.loads(MANIFEST_JSON.read_text())
        except json.JSONDecodeError:
            data = {}
    data[name] = {"caption": caption, "source": source, "generated": stamp}
    MANIFEST_JSON.write_text(json.dumps(data, indent=2, sort_keys=True))


def write_manifest_md():
    """Regenerate MANIFEST.md from the JSON, grouped by source."""
    if not MANIFEST_JSON.exists():
        print("no manifest.json yet")
        return
    data = json.loads(MANIFEST_JSON.read_text())

    by_source = {}
    for name, meta in sorted(data.items()):
        by_source.setdefault(meta["source"], []).append((name, meta))

    L = ["# QA screenshot manifest",
         "",
         f"**{len(data)} figures.** Auto-generated by `scripts/qa_common.write_manifest_md()` —",
         "do not hand-edit. Every figure carries its caption and generation timestamp burned",
         "into the image itself, so it stays self-explanatory if pasted into a slide.",
         "",
         "Naming convention: `<source>_<NN>_<description>.png`",
         ""]

    for source in sorted(by_source):
        L.append(f"## {source}")
        L.append("")
        L.append("| figure | what it shows | generated |")
        L.append("|---|---|---|")
        for name, meta in by_source[source]:
            cap = meta["caption"].replace("|", "\\|")
            L.append(f"| [{name}]({name}) | {cap} | {meta['generated']} |")
        L.append("")

    MANIFEST_MD.write_text("\n".join(L) + "\n")
    print(f"wrote {MANIFEST_MD.name} ({len(data)} figures)")


def resolve_catchments():
    """Same resolution order as aggregate_catchments, for consistent figures."""
    import geopandas as gpd

    from config import INTERIM, VECTORS

    for path, kind in [
        (VECTORS / "catchments.gpkg", "real"),
        (VECTORS / "catchments_PROVISIONAL.gpkg", "provisional"),
        (INTERIM / "catchments_FIXTURE_local_test_only.gpkg", "FIXTURE"),
    ]:
        if path.exists():
            gdf = gpd.read_file(path)
            if "catchment_id" not in gdf.columns and "id" in gdf.columns:
                gdf = gdf.rename(columns={"id": "catchment_id"})
            return gdf, kind
    return None, None


def fixture_warning(kind):
    """Text to burn into any figure derived from the stand-in catchments."""
    if kind == "FIXTURE":
        return (" CATCHMENTS ARE A LOCAL TEST FIXTURE, NOT MAHDI'S DELIVERABLE — "
                "geometry is 5 latitude bands, not a watershed delineation.")
    return ""


if __name__ == "__main__":
    write_manifest_md()
