"""Shared plumbing for QA figures: captioning, timestamping, manifest, basemaps.

Standing rule for this phase: if it isn't visible it isn't verified; if it's
verified it's screenshotted; if it's screenshotted it's named, captioned and
linked. `save_fig` enforces the last three mechanically so a figure cannot be
produced without a caption, and the manifest cannot drift from what is on disk.

Naming convention: <source>_<NN>_<description>.png
"""

import datetime as _dt
import json
import warnings

import contextily as cx
import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt

from pulga_config import QA

warnings.filterwarnings("ignore", category=UserWarning)

MANIFEST_JSON = QA / "manifest.json"
MANIFEST_MD = QA / "MANIFEST.md"

# Web Mercator: the native CRS of the tile providers. Basemap figures are drawn
# in 3857 rather than 4326 so tiles are used unwarped and at full sharpness, and
# so no aspect correction is needed (Mercator is conformal — shapes are locally
# true, which is the property a visual check depends on).
CRS_BASEMAP = "EPSG:3857"

SATELLITE = cx.providers.Esri.WorldImagery


def add_satellite(ax, zoom=13, attribution_size=5):
    """Esri WorldImagery under the current axes. Axes must already be in 3857."""
    try:
        cx.add_basemap(ax, source=SATELLITE, zoom=zoom, crs=CRS_BASEMAP,
                       attribution_size=attribution_size)
        return True
    except Exception as e:  # offline / tile server hiccup must not kill the run
        print(f"    ! basemap unavailable ({type(e).__name__}) — plotting without it")
        return False


def save_fig(fig, name, caption, source, dpi=150):
    """Save under QA/, stamp caption + UTC timestamp on the image, record it.

    `caption` is mandatory and is burned into the figure itself, so an image that
    gets copied into a slide deck still carries its own explanation.
    """
    if not name.endswith(".png"):
        name += ".png"
    stamp = _dt.datetime.now(_dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    fig.text(0.005, 0.004, caption, ha="left", va="bottom", fontsize=7.5,
             color="#222222", wrap=True)
    fig.text(0.995, 0.004, f"ReefShield Aqaba · Pulga · {stamp}", ha="right",
             va="bottom", fontsize=6.5, color="#777777")

    QA.mkdir(parents=True, exist_ok=True)
    path = QA / name
    fig.savefig(path, dpi=dpi, bbox_inches="tight", facecolor="white")
    plt.close(fig)

    _record(name, caption, source, stamp)
    print(f"    {name}")
    return path


def _record(name, caption, source, stamp):
    data = {}
    if MANIFEST_JSON.exists():
        try:
            data = json.loads(MANIFEST_JSON.read_text())
        except json.JSONDecodeError:
            data = {}
    data[name] = {"caption": caption, "source": source, "generated": stamp}
    MANIFEST_JSON.write_text(json.dumps(data, indent=2, sort_keys=True))


def write_manifest_md():
    """Regenerate MANIFEST.md from the JSON, grouped by source."""
    if not MANIFEST_JSON.exists():
        print("no manifest.json yet")
        return
    data = json.loads(MANIFEST_JSON.read_text())

    by_source = {}
    for name, meta in sorted(data.items()):
        by_source.setdefault(meta["source"], []).append((name, meta))

    L = ["# QA screenshot manifest",
         "",
         f"**{len(data)} figures.** Auto-generated by `scripts/qa_common.write_manifest_md()` —",
         "do not hand-edit. Every figure carries its caption and generation timestamp burned",
         "into the image itself, so it stays self-explanatory if pasted into a slide.",
         "",
         "Naming convention: `<source>_<NN>_<description>.png`",
         ""]

    for source in sorted(by_source):
        L.append(f"## {source}")
        L.append("")
        L.append("| figure | what it shows | generated |")
        L.append("|---|---|---|")
        for name, meta in by_source[source]:
            cap = meta["caption"].replace("|", "\\|")
            L.append(f"| [{name}]({name}) | {cap} | {meta['generated']} |")
        L.append("")

    # Account for every PNG in the directory, including ones this workstream did
    # not produce. Silently ignoring them would let the manifest claim to cover a
    # directory it only partly covers, and deleting them would destroy another
    # workstream's evidence.
    on_disk = {p.name for p in QA.glob("*.png")}
    foreign = sorted(on_disk - set(data))
    if foreign:
        L.append("## Produced by another workstream")
        L.append("")
        L.append("Present in this directory but not generated by Pulga's QA scripts, so")
        L.append("not captioned here. Listed so the directory is fully accounted for.")
        L.append("")
        for name in foreign:
            L.append(f"- [{name}]({name})")
        L.append("")

    missing = sorted(set(data) - on_disk)
    if missing:
        L.append("## Recorded but missing from disk")
        L.append("")
        L.append("These were manifested by an earlier run and are no longer present —")
        L.append("either renamed or deleted. Investigate rather than ignore.")
        L.append("")
        for name in missing:
            L.append(f"- `{name}`")
        L.append("")

    MANIFEST_MD.write_text("\n".join(L) + "\n")
    print(f"wrote {MANIFEST_MD.name} ({len(data)} Pulga figures, "
          f"{len(foreign)} from other workstreams, {len(missing)} missing)")


def prune_missing() -> list[str]:
    """Drop manifest entries whose PNG is gone. Call deliberately, never on write.

    `write_manifest_md` reports missing files instead of silently dropping them,
    because a figure vanishing usually means a QA script broke and that is worth
    seeing. This function exists for the other case: a figure that was renamed on
    purpose, where the stale entry is noise rather than signal.

    Used once when osm_04_culverts_all_27_numbered.png became
    osm_04_culverts_all_numbered.png — the AOI v2 re-clip took the culvert count
    from 27 to 46, so a count baked into a filename had become a lie.
    """
    if not MANIFEST_JSON.exists():
        return []
    data = json.loads(MANIFEST_JSON.read_text())
    on_disk = {p.name for p in QA.glob("*.png")}
    stale = sorted(set(data) - on_disk)
    for name in stale:
        del data[name]
    if stale:
        MANIFEST_JSON.write_text(json.dumps(data, indent=2, sort_keys=True))
        print(f"pruned {len(stale)} stale manifest entry/entries: {', '.join(stale)}")
    return stale


def resolve_catchments():
    """Same resolution order as aggregate_catchments, for consistent figures."""
    import geopandas as gpd

    from pulga_config import INTERIM, VECTORS

    for path, kind in [
        (VECTORS / "catchments.gpkg", "real"),
        (VECTORS / "catchments_PROVISIONAL.gpkg", "provisional"),
    ]:
        if path.exists():
            gdf = gpd.read_file(path)
            if "catchment_id" not in gdf.columns and "id" in gdf.columns:
                gdf = gdf.rename(columns={"id": "catchment_id"})
            return gdf, kind
    return None, None


def provenance_warning(kind):
    """Text to burn into any figure not built on the final catchment delineation.

    Replaces the old `fixture_warning`, which could no longer fire once the local
    synthetic fixture tier was removed on 2 Aug 2026. The live concern is now
    Mahdi's provisional seed: a figure built on it is still legitimate, but a reader
    must be able to see which delineation produced it.
    """
    if kind == "provisional":
        return (" CATCHMENTS ARE MAHDI'S PROVISIONAL SEED, not the final 30 m "
                "delineation — re-run once catchments.gpkg is published.")
    return ""


if __name__ == "__main__":
    write_manifest_md()
